name: env_214
channels:
  - defaults
dependencies:
  - python
  - pip:
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - scikit-learn
    - jupyterlab
    - torch
    - lightning
    - pyyaml
    - tqdm

